---
- name: Install Jenkins
# https://github.com/geerlingguy/ansible-role-java/issues/58
  gather_facts: True
  hosts: all
  # To run locally
  #hosts: localhost
  #connection: local
  become: yes

  vars_files:
    - vars/main.yml

  tasks:
    - name: Install prerequisites
      package:
        name: "{{ item }}"
        update_cache: yes
      with_items:
          - jq
      become: yes      

    # In order to push docker images to insecure registry special configuration is required.
    # https://docs.docker.com/registry/insecure/
    - name: Configure Jenkins to Access insecure docker registry
      template:
        src: daemon.json
        dest: "/etc/docker/daemon.json"
        owner: "{{ jenkins_process_user }}"
        group: "{{ jenkins_process_group }}"
        mode: 0777
      register: docker_insecure_registry_access
      when:
        - docker_insecure_registry_domain | length > 0

    - name: Immediately restart Docker for accessing insecure registry.
      service: name=docker state=restarted

    - name: Create a .ssh Directory before copying Keys
      file:
        path: "{{jenkins_home}}/.ssh"
        state: directory
        recurse: yes
        owner: "{{ jenkins_process_user }}"
        group: "{{ jenkins_process_group }}"    

#This is a very important step as the files being downloaded in workspace cease to take Jenkin's users permissions.
# sudo chown -R jenkins:jenkins /var/lib/jenkins/
    - name: Recursively Apply Permissions for Jenkins user in the jenkins home folder
      file:
        path: "{{jenkins_home}}"
        state: directory
        recurse: yes
        owner: "{{ jenkins_process_user }}"
        group: "{{ jenkins_process_group }}"
      become: yes         

    - name: Copy Private SSH Key of Staging Server for SSH Access
      copy:
        src: /vagrant/.vagrant/machines/staging.local/virtualbox/private_key
        dest: "{{jenkins_home}}/.ssh/staging.key"
        owner: "{{ jenkins_process_user }}"
        group: "{{ jenkins_process_group }}"
        mode: 0644
      become: yes 

    - name: Copy Private SSH Key of Production Server for SSH Access
      copy:
        src: /vagrant/.vagrant/machines/production.local/virtualbox/private_key
        dest: "{{jenkins_home}}/.ssh/production.key"
        owner: "{{ jenkins_process_user }}"
        group: "{{ jenkins_process_group }}"
        mode: 0644
      become: yes

    - name: Copy Private SSH Key of Archiver Server for SSH Access
      copy:
        src: /vagrant/.vagrant/machines/archiver.local/virtualbox/private_key
        dest: "{{jenkins_home}}/.ssh/archiver.key"
        owner: "{{ jenkins_process_user }}"
        group: "{{ jenkins_process_group }}"
        mode: 0644
      become: yes      

  roles:
    - role: provisioning/roles/geerlingguy.jenkins
      become: yes
      vars: 
        # Jenkins 
        # https://github.com/geerlingguy/ansible-role-jenkins/issues/269
        jenkins_version: "2.191"
        jenkins_admin_username: jenkins
        jenkins_admin_password: jenkins
        jenkins_http_port: 8080
        jenkins_plugins_install_dependencies: yes
        jenkins_package_state: present
        jenkins_java_options: "-Djenkins.install.runSetupWizard=false -Xms512m -Xmx1024m"
        jenkins_plugins:
          - git # Installs Credentials and SSH credentials plugins
          - ssh
          - ws-cleanup
          - timestamper
          - credentials-binding
          - ansicolor
          - workflow-aggregator
          - email-ext
          - blueocean
          - mailer
          - ssh-steps
          - monitoring
      
    - role: provisioning/roles/geerlingguy.docker
      become: yes
      vars:
        docker_users: ["{{ jenkins_process_user }}","vagrant"]
    - role: provisioning/roles/ansible-role-maven
    - role: provisioning/roles/geerlingguy.nodejs
      become: yes
      vars:
        nodejs_version: "12.x"
        nodejs_npm_global_packages: ["rimraf","mkdirp","copyfiles"]