- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add an Apt signing key, uses whichever key is at the URL
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
    state: present

- name: Install elasticsearch and pre-requisites
  package:
    name: "{{ item }}"
    update_cache: yes
  with_items:
      - apt-transport-https
      - elasticsearch

- name: Copy the config file
  template:
    src: elasticsearch.yml.j2
    dest: "/etc/elasticsearch/elasticsearch.yml"
  notify: Restart Elasticsearch

