- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add an Apt signing key, uses whichever key is at the URL
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
    state: present

- name: Install logstash and pre-requisites
  package:
    name: "{{ item }}"
    update_cache: yes
  with_items:
      - apt-transport-https
      - logstash

- name: Copy the config file
  template:
    src: logstash.conf.j2
    dest: "/etc/logstash/conf.d/logstash.conf"

- name: Starting and Enabling logstash service
  service:
    name: logstash
    state: started
    enabled: yes
  changed_when: false
  register: get_result
  until: get_result is success
  retries: 3
  delay: 2

